scroll_id: "choju-giga-yamazaki-kou"
volume_num: 1
theme_id: "choju-giga"
folder: "emakimono"
scenes:
  - scene_id: 1
    common_id: "choju_m_01"
    title: "兎と猿の川遊び"
    range: [1, 4]  # 1から4まで（1, 2, 3, 4 を含む）
  - scene_id: 2
    common_id: "choju_m_02"
    title: "兎と蛙の神事弓くらべ"
    range: [5, 10] # 5から10まで（5, 6, 7, 8, 9, 10 を含む）
  - scene_id: 3
    common_id: "choju_m_03"
    title: "猿僧正、神供を賜る"
    range: [11, 12]
  - scene_id: 4
    common_id: "choju_m_04"
    title: "猿と蛙の争い"
    range: [13, 14]
  - scene_id: 5
    common_id: "choju_m_05"
    title: "田楽神事を見守る"
    range: [15, 16]
  - scene_id: 6
    common_id: "choju_m_06"
    title: "兎と蛙の神聖なる相撲"
    range: [17, 18]
  - scene_id: 7
    common_id: "choju_m_07"
    title: "猿、双六盤を運ぶ"
    range: [19, 19] # 1枚のみの場合も [start, end] 形式にする
  - scene_id: 8
    common_id: "choju_m_08"
    title: "猿僧正、年忌法要を司る"
    range: [20, 21]
  - scene_id: 9
    common_id: "choju_m_09"
    title: "猿僧正へ奉げられた供物"
    range: [22, 23]
