scroll_id: "jigokusoushi_genke"
volume_num: 1
theme_id: "jigoku"
folder: "emakimono"

metadata:
  id: 13
  title: "地獄草紙（原家本）"
  titleen: "jigokusoushi_genke"
  author: ""
  authoren: ""
  edition: ""
  era: "平安"
  eraen: "heiann"
  type: "絵巻"
  typeen: "emaki"
  desc: ""
  descen: ""
  thumb: "/jigokusoushi_genke_thumb.webp"
  thumb2: "/jigokusoushi_genke_thumb.webp"
  backgroundImage: "/washi-pattern-01.webp"
  video: ""
  encodeUrl: ""
  sourceImageUrl: "https://colbase.nich.go.jp/collection_items/narahaku/644-0?locale=ja"
  sourceImage: "地獄草紙 （ColBase）"
  sourceEkotoba: ""
  favorite: false
  kotobagaki: true
  readMore: false
  gif: ""
  metadesc: ""
  reference:
    - type: "書籍"
      url: "https://rb.gy/r3nghf"
      title: "『餓鬼草紙 地獄草紙 病草紙 九相詩絵巻』（日本絵巻大成7 中央公論社）"
  keywords:
    - { name: "地獄", id: "hell", slug: "hell" }
    - { name: "仏教", id: "buddhism", slug: "buddhism" }
    - { name: "鬼", id: "demon", slug: "demon" }

scenes:
  - id: 1
    title: "屎糞所"
    titleen: "Shifunsho"
    range: [1, 1]
  - id: 2
    title: "函量所"
    titleen: "Kanryosho"
    range: [2, 2]
  - id: 3
    title: "鉄鎧所"
    titleen: "Tetsugaisho"
    range: [3, 3]
  - id: 4
    title: "鶏地獄"
    titleen: "Tori Jigoku"
    range: [4, 4]
  - id: 5
    title: "黒雲沙"
    titleen: "Kokunsha"
    range: [5, 5]
  - id: 6
    title: "濃血所"
    titleen: "Noketsusho"
    range: [6, 6]
  - id: 7
    title: "狐狼地獄"
    titleen: "Koro Jigoku"
    range: [7, 7]
