[
  {
    cat: "ekotoba",
    chapter: " 【第０相】生前相",
    kobun: "",
    gendaibun: "",
    desc: "",
    load: "",
    srcSp: "",
    srcTb: "",
    src: "",
    name: "",
    srcWidth: "",
    srcHeight: "",
    linkId: 0,
    ekotobaId: 0,
  },
  {
    cat: "image",
    chapter: "",
    kobun: "",
    gendaibun: "",
    desc: "",
    load: "True",
    srcSp: "/kusouzu_01-375.webp",
    srcTb: "/kusouzu_01-800.webp",
    src: "/kusouzu_01-1080.webp",
    name: "kusouzu_01.webp",
    srcWidth: "1757",
    srcHeight: "1080",
    linkId: 1,
  },
  {
    cat: "ekotoba",
    chapter: "【第一相】 新死相",
    kobun: "",
    gendaibun: "",
    desc: "",
    load: "",
    srcSp: "",
    srcTb: "",
    src: "",
    name: "",
    srcWidth: "",
    srcHeight: "",
    linkId: 2,
    ekotobaId: 1,
  },
  {
    cat: "image",
    chapter: "",
    kobun: "",
    gendaibun: "",
    desc: "",
    load: "True",
    srcSp: "/kusouzu_02-375.webp",
    srcTb: "/kusouzu_02-800.webp",
    src: "/kusouzu_02-1080.webp",
    name: "kusouzu_02.webp",
    srcWidth: "1693",
    srcHeight: "1080",
    linkId: 3,
  },
  {
    cat: "ekotoba",
    chapter:
      "【第二相】 <ruby><rb>脹相</rb><rp>（</rp><rt>ちょうそう</rt><rp>）</rp></ruby> ",
    kobun: "",
    gendaibun: "",
    desc: "これらの死屍は、顔色が黒ずみ、身体が硬直して手足が花を散らしたようにあちこちを向く、膨脹した身体が風をはらんでふくらんだ革袋のようである。九つの孔からは、汚物が流れ溢れ、はなはだ穢れ醜悪である。行者は自らおもう、我が身もこれと同じであるし、未だ愛着を断ち切ることのできない愛人もまた、これと同じである。この相を見れば、心が少々定まり徐々に落ち着くのである。",
    load: "",
    srcSp: "",
    srcTb: "",
    src: "",
    name: "",
    srcWidth: "",
    srcHeight: "",
    linkId: 4,
    ekotobaId: 2,
  },
  {
    cat: "image",
    chapter: "",
    kobun: "",
    gendaibun: "",
    desc: "",
    load: "False",
    srcSp: "/kusouzu_03-375.webp",
    srcTb: "/kusouzu_03-800.webp",
    src: "/kusouzu_03-1080.webp",
    name: "kusouzu_03.webp",
    srcWidth: "1708",
    srcHeight: "1080",
    linkId: 5,
  },
  {
    cat: "ekotoba",
    chapter:
      "【第三相】 <ruby><rb>壊相</rb><rp>（</rp><rt>えそう</rt><rp>）</rp></ruby> ",
    kobun: "",
    gendaibun: "",
    desc: "またたく間に、この膨張した屍は、風に吹かれ日に曝されて、皮や肉が破れ壊れ、身体が<ruby><rb>坼裂</rb><rp>（</rp><rt>たくれつ</rt><rp>）</rp></ruby>して形や色が変わってしまい、識別不可能となる。これを、壊相と名づける。",
    load: "",
    srcSp: "",
    srcTb: "",
    src: "",
    name: "",
    srcWidth: "",
    srcHeight: "",
    linkId: 6,
    ekotobaId: 3,
  },
  {
    cat: "image",
    chapter: "",
    kobun: "",
    gendaibun: "",
    desc: "",
    load: "False",
    srcSp: "/kusouzu_04-375.webp",
    srcTb: "/kusouzu_04-800.webp",
    src: "/kusouzu_04-1080.webp",
    name: "kusouzu_04.webp",
    srcWidth: "1685",
    srcHeight: "1080",
    linkId: 7,
  },
  {
    cat: "ekotoba",
    chapter:
      "【第四相】 <ruby><rb>血塗相</rb><rp>（</rp><rt>けちずそう</rt><rp>）</rp></ruby> ",
    kobun: "",
    gendaibun: "",
    desc: "<ruby><rb>坼裂</rb><rp>（</rp><rt>たくれつ</rt><rp>）</rp></ruby>したところから血が溢れ出る。あちこちに飛び散り溜り、所々を斑に染める、溢れて地面に染み込み悪臭が漂う、これを血塗相とする。",
    load: "",
    srcSp: "",
    srcTb: "",
    src: "",
    name: "",
    srcWidth: "",
    srcHeight: "",
    linkId: 8,
    ekotobaId: 4,
  },
  {
    cat: "image",
    chapter: "",
    kobun: "",
    gendaibun: "",
    desc: "",
    load: "False",
    srcSp: "/kusouzu_05-375.webp",
    srcTb: "/kusouzu_05-800.webp",
    src: "/kusouzu_05-1080.webp",
    name: "kusouzu_05.webp",
    srcWidth: "1682",
    srcHeight: "1080",
    linkId: 9,
  },
  {
    cat: "ekotoba",
    chapter:
      "【第五相】 <ruby><rb>膿爛相</rb><rp>（</rp><rt>のうらんそう</rt><rp>）</rp></ruby>",
    kobun: "",
    gendaibun: "",
    desc: "膿爛し流れ潰える死体を見る。肉が溶けて流れ、火をつけた蝋燭のようである。これを膿爛相と名づける。",
    load: "",
    srcSp: "",
    srcTb: "",
    src: "",
    name: "",
    srcWidth: "",
    srcHeight: "",
    linkId: 10,
    ekotobaId: 5,
  },
  {
    cat: "image",
    chapter: "",
    kobun: "",
    gendaibun: "",
    desc: "",
    load: "False",
    srcSp: "/kusouzu_06-375.webp",
    srcTb: "/kusouzu_06-800.webp",
    src: "/kusouzu_06-1080.webp",
    name: "kusouzu_06.webp",
    srcWidth: "1705",
    srcHeight: "1080",
    linkId: 11,
  },
  {
    cat: "ekotoba",
    chapter:
      "【第六相】 <ruby><rb>青瘀相</rb><rp>（</rp><rt>しょうおそう</rt><rp>）</rp></ruby>",
    kobun: "",
    gendaibun: "",
    desc: "残りの皮やあまった肉が風や日に乾き炙られ、臭く腐敗し黒ずむのを見る。半ば青く半ば傷んで、痩せて皮がたるんでいる、これを青瘀相とする。",
    load: "",
    srcSp: "",
    srcTb: "",
    src: "",
    name: "",
    srcWidth: "",
    srcHeight: "",
    linkId: 12,
    ekotobaId: 6,
  },
  {
    cat: "image",
    chapter: "",
    kobun: "",
    gendaibun: "",
    desc: "",
    load: "False",
    srcSp: "/kusouzu_07-375.webp",
    srcTb: "/kusouzu_07-800.webp",
    src: "/kusouzu_07-1080.webp",
    name: "kusouzu_07.webp",
    srcWidth: "1711",
    srcHeight: "1080",
    linkId: 13,
  },
  {
    cat: "ekotoba",
    chapter:
      "【第七相】 <ruby><rb>噉相</rb><rp>（</rp><rt>たんそう</rt><rp>）</rp></ruby>",
    kobun: "",
    gendaibun: "",
    desc: "この屍が狐、狼、鳶、鷲に噉相されるのを見る、肉片を奪い争い、引き裂いて散り散りになる、これを噉相とする。",
    load: "",
    srcSp: "",
    srcTb: "",
    src: "",
    name: "",
    srcWidth: "",
    srcHeight: "",
    linkId: 14,
    ekotobaId: 7,
  },
  {
    cat: "image",
    chapter: "",
    kobun: "",
    gendaibun: "",
    desc: "",
    load: "False",
    srcSp: "/kusouzu_08-375.webp",
    srcTb: "/kusouzu_08-800.webp",
    src: "/kusouzu_08-1080.webp",
    name: "kusouzu_08.webp",
    srcWidth: "2180",
    srcHeight: "1080",
    linkId: 15,
  },
  {
    cat: "ekotoba",
    chapter:
      "【第八相】 <ruby><rb>散相</rb><rp>（</rp><rt>さんそう</rt><rp>）</rp></ruby>",
    kobun: "",
    gendaibun: "",
    desc: "頭と手が異なるところにあるのを見る。五臓が散らばってもはや収斂しない。これを散相とする。",
    load: "",
    srcSp: "",
    srcTb: "",
    src: "",
    name: "",
    srcWidth: "",
    srcHeight: "",
    linkId: 16,
    ekotobaId: 8,
  },
  {
    cat: "image",
    chapter: "",
    kobun: "",
    gendaibun: "",
    desc: "",
    load: "False",
    srcSp: "/kusouzu_09-375.webp",
    srcTb: "/kusouzu_09-800.webp",
    src: "/kusouzu_09-1080.webp",
    name: "kusouzu_09.webp",
    srcWidth: "1221",
    srcHeight: "1080",
    linkId: 17,
  },
  {
    cat: "ekotoba",
    chapter:
      "【第九相】 <ruby><rb> 骨相</rb><rp>（</rp><rt>こつそう</rt><rp>）</rp></ruby>",
    kobun: "",
    gendaibun: "",
    desc: "二種の骨があるのを見る。一つは濃膏を帯び、一つは純白で清浄である。ある時は一具の骨で、またある時は散乱している。",
    load: "",
    srcSp: "",
    srcTb: "",
    src: "",
    name: "",
    srcWidth: "",
    srcHeight: "",
    linkId: 18,
    ekotobaId: 9,
  },
  {
    cat: "image",
    chapter: "",
    kobun: "",
    gendaibun: "",
    desc: "",
    load: "False",
    srcSp: "/kusouzu_10-375.webp",
    srcTb: "/kusouzu_10-800.webp",
    src: "/kusouzu_10-1080.webp",
    name: "kusouzu_10.webp",
    srcWidth: "1771",
    srcHeight: "1080",
    linkId: 19,
  },
];
