const dataSuibokuga = [
  {
    id: 37,
    title: "四季山水図巻（山水長巻）",
    titleen: "sessyu_sikisansuizu",
    author: "雪舟",
    authoren:"sesshu",
    backgroundImage: "/washi-pattern-01.webp",
    video: "",
    thumb: "/sessyu_sikisansuizu_thumb.webp",
    thumb2: "/sessyu_sikisansuizu_thumb.webp",
    metadesc: "",
    desc: "",
    era: "室町",
    eraen: "muromachi",
    gif: "",
    type: "水墨画",
    typeen: "suibokuga",
    kotobagaki: true,
    sourceImageUrl: "https://ja.wikipedia.org/wiki/%E9%9B%AA%E8%88%9F",
    sourceImage: "雪舟（ウィキペディア）",
    reference: "",
    sourceEkotoba: "",
    emakis: [
      {
        load: true,
        cat: "image",
        srcSp: "/sessyu_sikisansuizu_01-375.webp",
        srcTb: "/sessyu_sikisansuizu_01-800.webp",
        src: "/sessyu_sikisansuizu_01-1080.webp",
        name: "sessyu_sikisansuizu_01.webp",
      },
      {
        load: true,
        cat: "image",
        srcSp: "/sessyu_sikisansuizu_02-375.webp",
        srcTb: "/sessyu_sikisansuizu_02-800.webp",
        src: "/sessyu_sikisansuizu_02-1080.webp",
        name: "sessyu_sikisansuizu_02.webp",
      },
      {
        load: true,
        cat: "image",
        srcSp: "/sessyu_sikisansuizu_03-375.webp",
        srcTb: "/sessyu_sikisansuizu_03-800.webp",
        src: "/sessyu_sikisansuizu_03-1080.webp",
        name: "sessyu_sikisansuizu_03.webp",
      },
      {
        load: true,
        cat: "image",
        srcSp: "/sessyu_sikisansuizu_04-375.webp",
        srcTb: "/sessyu_sikisansuizu_04-800.webp",
        src: "/sessyu_sikisansuizu_04-1080.webp",
        name: "sessyu_sikisansuizu_04.webp",
      },

      {
        load: false,
        cat: "image",
        srcSp: "/sessyu_sikisansuizu_05-375.webp",
        srcTb: "/sessyu_sikisansuizu_05-800.webp",
        src: "/sessyu_sikisansuizu_05-1080.webp",
        name: "sessyu_sikisansuizu_05.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/sessyu_sikisansuizu_06-375.webp",
        srcTb: "/sessyu_sikisansuizu_06-800.webp",
        src: "/sessyu_sikisansuizu_06-1080.webp",
        name: "sessyu_sikisansuizu_06.webp",
      },

      {
        load: false,
        cat: "image",
        srcSp: "/sessyu_sikisansuizu_07-375.webp",
        srcTb: "/sessyu_sikisansuizu_07-800.webp",
        src: "/sessyu_sikisansuizu_07-1080.webp",
        name: "sessyu_sikisansuizu_07.webp",
      },

      {
        load: false,
        cat: "image",
        srcSp: "/sessyu_sikisansuizu_08-375.webp",
        srcTb: "/sessyu_sikisansuizu_08-800.webp",
        src: "/sessyu_sikisansuizu_08-1080.webp",
        name: "sessyu_sikisansuizu_08.webp",
      },

      {
        load: false,
        cat: "image",
        srcSp: "/sessyu_sikisansuizu_09-375.webp",
        srcTb: "/sessyu_sikisansuizu_09-800.webp",
        src: "/sessyu_sikisansuizu_09-1080.webp",
        name: "sessyu_sikisansuizu_09.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/sessyu_sikisansuizu_10-375.webp",
        srcTb: "/sessyu_sikisansuizu_10-800.webp",
        src: "/sessyu_sikisansuizu_10-1080.webp",
        name: "sessyu_sikisansuizu_10.webp",
      },

      {
        load: false,
        cat: "image",
        srcSp: "/sessyu_sikisansuizu_11-375.webp",
        srcTb: "/sessyu_sikisansuizu_11-800.webp",
        src: "/sessyu_sikisansuizu_11-1080.webp",
        name: "sessyu_sikisansuizu_11.webp",
      },

      {
        load: false,
        cat: "image",
        srcSp: "/sessyu_sikisansuizu_12-375.webp",
        srcTb: "/sessyu_sikisansuizu_12-800.webp",
        src: "/sessyu_sikisansuizu_12-1080.webp",
        name: "sessyu_sikisansuizu_12.webp",
      },
    ],
  },
];

export default dataSuibokuga