#!/usr/bin/env python3
"""
generate_actions.py — Rule-based actions.md + actions.json from merged.json.

Used by GitHub Actions to smoke-test the Automation review path (Issue creation).
Cursor Automation may produce richer narrative actions; this is the CI baseline.

Usage:
  py -3.14 scripts/analytics/generate_actions.py --report-dir analytics/reports/2026-07-24
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from _paths import REPO_ROOT  # noqa: E402

FLAG_PRIORITY = {
    "impressions_no_clicks": ("P1", "meta / title-description"),
    "high_impressions_low_ctr": ("P1", "meta / snippet"),
    "high_traffic_low_engagement": ("P2", "viewer UX"),
    "high_image_fallback": ("P2", "CDN / image loading"),
}


def _display_name(row: dict) -> str:
    return row.get("title") or row.get("slug") or "unknown"


def _format_top_row(row: dict) -> str:
    title = _display_name(row)
    slug = row.get("slug", "")
    return (
        f"### {_display_name(row)}\n\n"
        f"- slug: `{slug}`\n"
        f"- GA4 sessions: {row.get('ga4_sessions', 0)}\n"
        f"- GSC clicks: {row.get('gsc_clicks', 0)} / imp {row.get('gsc_impressions', 0)}\n"
        f"- CTR: {row.get('gsc_ctr', 0)}\n"
    )


def _format_needs_row(row: dict) -> str:
    flags = ", ".join(row.get("insight_flags") or [])
    delta = row.get("delta") or {}
    delta_text = ""
    if delta:
        delta_text = (
            f"- Δ sessions: {delta.get('ga4_sessions', 0)}, "
            f"Δ GSC clicks: {delta.get('gsc_clicks', 0)}\n"
        )
    return (
        f"### {_display_name(row)} — {flags}\n\n"
        f"- slug: `{row.get('slug', '')}`\n"
        f"- GSC: {row.get('gsc_clicks', 0)} clicks / {row.get('gsc_impressions', 0)} imp\n"
        f"- GA4 sessions: {row.get('ga4_sessions', 0)}\n"
        f"- top query: {row.get('top_query') or '(none)'}\n"
        f"{delta_text}"
    )


def _recommendations(rows: list[dict]) -> list[dict]:
    items: list[dict] = []
    seen_slugs: set[str] = set()

    flagged = [r for r in rows if r.get("insight_flags")]
    flagged.sort(key=lambda r: (r.get("gsc_impressions", 0), r.get("ga4_sessions", 0)), reverse=True)

    for row in flagged:
        slug = row.get("slug") or ""
        if not slug or slug in seen_slugs:
            continue
        flags = row.get("insight_flags") or []
        priority, layer = FLAG_PRIORITY.get(flags[0], ("P3", "general"))
        seen_slugs.add(slug)
        title = f"{layer} for {_display_name(row)}"
        body = (
            f"**Report:** `{row.get('_report_dir', '')}`\n\n"
            f"**Flags:** {', '.join(flags)}\n\n"
            f"| Metric | Value |\n|--------|-------|\n"
            f"| GSC impressions | {row.get('gsc_impressions', 0)} |\n"
            f"| GSC clicks | {row.get('gsc_clicks', 0)} |\n"
            f"| GA4 sessions | {row.get('ga4_sessions', 0)} |\n"
            f"| Top query | {row.get('top_query') or '(none)'} |\n\n"
            f"**Proposal:** Review meta, internal links, or viewer UX for `{slug}`.\n\n"
            f"_Generated by `scripts/analytics/generate_actions.py` (CI smoke test)._"
        )
        items.append(
            {
                "priority": priority,
                "slug": slug,
                "title": title,
                "body": body,
                "flags": flags,
            }
        )
        if len(items) >= 6:
            break

    # Pad with high-traffic rows if few flags
    if len(items) < 3:
        by_sessions = sorted(rows, key=lambda r: r.get("ga4_sessions", 0), reverse=True)
        for row in by_sessions:
            slug = row.get("slug") or ""
            if not slug or slug in seen_slugs:
                continue
            seen_slugs.add(slug)
            items.append(
                {
                    "priority": "P3",
                    "slug": slug,
                    "title": f"Monitor traffic for {_display_name(row)}",
                    "body": (
                        f"High traffic row without strong flags.\n\n"
                        f"- GA4 sessions: {row.get('ga4_sessions', 0)}\n"
                        f"- GSC impressions: {row.get('gsc_impressions', 0)}\n"
                    ),
                    "flags": row.get("insight_flags") or [],
                }
            )
            if len(items) >= 3:
                break

    return items


def generate(report_dir: Path) -> dict:
    merged_path = report_dir / "merged.json"
    if not merged_path.is_file():
        raise FileNotFoundError(f"Missing {merged_path.relative_to(REPO_ROOT)}")

    merged = json.loads(merged_path.read_text(encoding="utf-8-sig"))
    rows = merged.get("rows") or []
    for row in rows:
        row["_report_dir"] = report_dir.name

    with_sessions = [r for r in rows if int(r.get("ga4_sessions") or 0) > 0]
    top = sorted(with_sessions, key=lambda r: r.get("ga4_sessions", 0), reverse=True)[:3]

    flagged = [r for r in rows if r.get("insight_flags")]
    flagged.sort(key=lambda r: r.get("gsc_impressions", 0), reverse=True)
    needs = flagged[:3]

    recommendations = _recommendations(rows)

    summary_path = report_dir / "summary.md"
    period = ""
    if summary_path.is_file():
        for line in summary_path.read_text(encoding="utf-8").splitlines():
            if line.startswith("- Period:"):
                period = line.removeprefix("- Period:").strip()
                break

    md_lines = [
        f"# Analytics Actions — {report_dir.name}",
        "",
        f"**Period:** {period or '(see summary.md)'}",
        "**Source:** CI smoke test (`generate_actions.py`) — Cursor Automation may replace with richer analysis.",
        "",
        "## Top performers (3)",
        "",
    ]
    for r in top:
        md_lines.append(_format_top_row(r))
    if not top:
        md_lines.append("- No rows with GA4 sessions\n")

    md_lines.extend(["", "## Needs improvement (3)", ""])
    for r in needs:
        md_lines.append(_format_needs_row(r))
    if not needs:
        md_lines.append("- No insight_flags in merged.json\n")

    md_lines.extend(["", "## Recommended actions (prioritized P1–P3)", ""])
    for item in recommendations:
        md_lines.append(
            f"- **{item['priority']}** `{item['slug']}`: {item['title']} "
            f"({', '.join(item['flags']) or 'monitor'})"
        )
    md_lines.append("")

    breakdown = merged.get("fallback_reason_breakdown") or {}
    if breakdown:
        total = sum(breakdown.values())
        if total > 0:
            md_lines.extend(["", "## Fallback reasons (image_load_fallback)", ""])
            for reason, count in breakdown.items():
                pct = round(count / total * 100, 1)
                md_lines.append(f"- `{reason}`: {count} ({pct}%)")
            md_lines.append("")

    geo_clusters = merged.get("education_geo_clusters") or []
    geo_flags = merged.get("education_geo_insight_flags") or []
    md_lines.extend(["", "## Education geo clusters (weak proxy)", ""])
    if geo_flags:
        md_lines.append(f"- flags: {', '.join(f'`{f}`' for f in geo_flags)}")
    if geo_clusters:
        for c in geo_clusters[:5]:
            md_lines.append(
                f"- `{c.get('level')}` **{c.get('name')}** "
                f"({c.get('country') or '—'}): {c.get('sessions', 0)} sessions"
            )
        md_lines.append("- ※ 教育利用の弱い代理。確定ではない。")
    else:
        md_lines.append("- No region/city clusters above threshold\n")

    slow = merged.get("image_load_slow_breakdown") or {}
    if slow:
        md_lines.extend(["", "## image_load_slow (by emaki)", ""])
        for slug, count in sorted(slow.items(), key=lambda kv: kv[1], reverse=True)[:5]:
            md_lines.append(f"- `{slug}`: {count}")
        md_lines.append("")

    payload = {
        "report_date": report_dir.name,
        "period": period,
        "previous_report": merged.get("previous_report"),
        "fallback_reason_breakdown": breakdown,
        "education_geo_clusters": geo_clusters,
        "education_geo_insight_flags": geo_flags,
        "recommendations": recommendations,
    }

    actions_md = report_dir / "actions.md"
    actions_json = report_dir / "actions.json"
    actions_md.write_text("\n".join(md_lines), encoding="utf-8")
    actions_json.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")

    return {
        "actions_md": str(actions_md.relative_to(REPO_ROOT)),
        "actions_json": str(actions_json.relative_to(REPO_ROOT)),
        "recommendation_count": len(recommendations),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate actions.md/json from merged.json")
    parser.add_argument("--report-dir", type=Path, required=True)
    args = parser.parse_args(argv)

    try:
        result = generate(args.report_dir.resolve())
    except Exception as exc:
        print(f"generate_actions failed: {exc}", file=sys.stderr)
        return 1

    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
