const allKeywords = [
  { name: "戯画", id: "caricature", slug: "caricature" },
  { name: "動物", id: "animal", slug: "animal" },
  { name: "鳥羽絵", id: "tobae", slug: "tobae" },
  { name: "年中行事", id: "annualevent", slug: "annualevent" },
  { name: "霊獣", id: "spiritualbeast", slug: "spiritualbeast" },
  { name: "遊戯", id: "game", slug: "game" },
  { name: "説話", id: "story", slug: "story" },
  { name: "火事", id: "fire", slug: "fire" },
  { name: "市場", id: "market", slug: "market" },
  { name: "蹴鞠", id: "kemari", slug: "kemari" },
  { name: "陰陽師", id: "onmyoji", slug: "onmyoji" },
  { name: "中将", id: "lieutenantgeneral", slug: "lieutenantgeneral" },
  { name: "双六", id: "sugoroku", slug: "sugoroku" },
  { name: "鬼", id: "demon", slug: "demon" },
  { name: "朱雀門", id: "suzakumon", slug: "suzakumon" },
  { name: "天神", id: "tenjin", slug: "tenjin" },
  { name: "無常", id: "impermanence", slug: "impermanence" },
  { name: "仏教", id: "buddhism", slug: "buddhism" },
  { name: "死生観", id: "lifeandodeath", slug: "lifeandodeath" },
  { name: "解剖学", id: "anatomy", slug: "anatomy" },
  { name: "和歌", id: "waka", slug: "waka" },
  { name: "吉野", id: "yoshino", slug: "yoshino" },
  { name: "熊野", id: "kumano", slug: "kumano" },
  { name: "桜", id: "cherry", slug: "cherry" },
  { name: "地獄", id: "hell", slug: "hell" },
  { name: "巫女", id: "shrinemaiden", slug: "shrinemaiden" },
  { name: "出産", id: "childbirth", slug: "childbirth" },
  { name: "六道", id: "sixpaths", slug: "sixpaths" },
  { name: "風景", id: "scenery", slug: "scenery" },
  { name: "写生", id: "sketch", slug: "sketch" },
  { name: "富士山", id: "fujimountain", slug: "fujimountain" },
  { name: "月", id: "moon", slug: "moon" },
  { name: "インド", id: "india", slug: "india" },
  { name: "虹", id: "rainbow", slug: "rainbow" },
  { name: "武士", id: "samurai", slug: "samurai" },
  { name: "結婚", id: "marry", slug: "marry" },
  { name: "連続式", id: "continuoustype", slug: "continuoustype" },
  { name: "鳥", id: "bird", slug: "bird" },
];

export default allKeywords;
