const data = [
  {
    title: "鳥獣人物戯画絵巻",
    titleen: "cyoujyujinbutsugiga_kou",
    author: "鳥羽僧正覚猷",
    edition: "甲巻",
    backgroundImage: "images/110310200304.webp",
    thumb: "/cyoujyuu_yamazaki_kou_thumb.webp",
    thumb2: "/cyoujyuu_yamazaki_kou_thumb2.webp",
    srcFirstView: "/cyoujyuu_yamazaki_kou_01-1080.webp",
    video: "https://youtu.be/Si8NzY2drSg",
    gif: "/img/cyoujyuu_yamazaki_kou.mp4",
    era: "平安時代末期",
    metadesc:
      "鳥獣人物戯画絵巻甲巻の全シーンを横スクロールでご覧になることができます。猿と蛙の喧嘩はなぜ起きたのか？、兎と蛙の相撲の結末は？、猫と鼠の思わぬ共演！？、などなど動物たちの生き生きとした表情を、心ゆくまでご覧ください☆",
    desc: "平安時代（12世紀）に描かれた鳥獣人物戯画絵巻 甲巻の摸本。有名な猿と蛙の喧嘩、兎と蛙の相撲のほか、田楽、賭弓など、当時ミヤコで流行っていた様々な遊びに動物が興じる姿が、表情豊かに描かれている。摸本や断簡には競馬や双六遊び、高跳びなど、現在知られている絵巻とは異なるモチーフの遊びが描かれている。そもそもははもっと長大な絵巻だったようだ。",
    readMore: false,
    type: "連続式絵巻",
    typeColor: "renzokushiki",
    sourceImage: "鳥獣人戯画絵巻 摸本（山崎董詮画 国立博物館）",
    emakis: [
      {
        cat: "ekotoba",
        chapter: "兎と猿の水遊び ",
        kobun: "",
        gendaibun: "",
      },
      {
        load: true,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_01-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_01-800.webp",
        src: "/cyoujyuu_yamazaki_kou_01-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },

      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_02-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_02-800.webp",
        src: "/cyoujyuu_yamazaki_kou_02-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_03-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_03-800.webp",
        src: "/cyoujyuu_yamazaki_kou_03-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_04-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_04-800.webp",
        src: "/cyoujyuu_yamazaki_kou_04-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        cat: "ekotoba",
        chapter: "兎と蛙の賭弓 ",
        kobun: "",
        gendaibun: "",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_05-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_05-800.webp",
        src: "/cyoujyuu_yamazaki_kou_05-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_06-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_06-800.webp",
        src: "/cyoujyuu_yamazaki_kou_06-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_07-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_07-800.webp",
        src: "/cyoujyuu_yamazaki_kou_07-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_08-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_08-800.webp",
        src: "/cyoujyuu_yamazaki_kou_08-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_09-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_09-800.webp",
        src: "/cyoujyuu_yamazaki_kou_09-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_10-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_10-800.webp",
        src: "/cyoujyuu_yamazaki_kou_10-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        cat: "ekotoba",
        chapter: "禄の物を受ける猿僧正",
        kobun: "",
        gendaibun: "",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_11-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_11-800.webp",
        src: "/cyoujyuu_yamazaki_kou_11-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_12-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_12-800.webp",
        src: "/cyoujyuu_yamazaki_kou_12-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        cat: "ekotoba",
        chapter: "猿と蛙の喧嘩",
        kobun: "",
        gendaibun: "",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_13-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_13-800.webp",
        src: "/cyoujyuu_yamazaki_kou_13-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_14-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_14-800.webp",
        src: "/cyoujyuu_yamazaki_kou_14-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        cat: "ekotoba",
        chapter: "田楽見物",
        kobun: "",
        gendaibun: "",
      },
      {
        load: false,
        srcSp: "/cyoujyuu_yamazaki_kou_15-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_15-800.webp",
        src: "/cyoujyuu_yamazaki_kou_15-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_16-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_16-800.webp",
        src: "/cyoujyuu_yamazaki_kou_16-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        cat: "ekotoba",
        chapter: "兎と蛙の相撲",
        kobun: "",
        gendaibun: "",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_17-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_17-800.webp",
        src: "/cyoujyuu_yamazaki_kou_17-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_18-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_18-800.webp",
        src: "/cyoujyuu_yamazaki_kou_18-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        cat: "ekotoba",
        chapter: "双六盤を運ぶ猿",
        kobun: "",
        gendaibun: "",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_19-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_19-800.webp",
        src: "/cyoujyuu_yamazaki_kou_19-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        cat: "ekotoba",
        chapter: "周忌法会の導師をつとめる猿僧正",
        kobun: "",
        gendaibun: "",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_20-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_20-800.webp",
        src: "/cyoujyuu_yamazaki_kou_20-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_21-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_21-800.webp",
        src: "/cyoujyuu_yamazaki_kou_21-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        cat: "ekotoba",
        chapter: "猿僧正への僧供",
        kobun: "",
        gendaibun: "",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_22-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_22-800.webp",
        src: "/cyoujyuu_yamazaki_kou_22-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/cyoujyuu_yamazaki_kou_23-375.webp",
        srcTb: "/cyoujyuu_yamazaki_kou_23-800.webp",
        src: "/cyoujyuu_yamazaki_kou_23-1080.webp",
        name: "鳥獣人物戯画絵巻甲巻摸本の画像",
      },
    ],
  },
];
export default data;
