const dataByoubus = [
  {
    id: 16,
    title: "松島図屏風",
    titleen: "matsusima",
    author: "俵屋宗達",
    backgroundImage: "/washi-pattern-01.webp",
    video: "",
    thumb: "/matsusima_thumb.webp",
    thumb2: "/matsusima_thumb.webp",
    metadesc: "",
    desc: "",
    era: "安土・桃山",
    eraen: "aduchimomoyama",
    gif: "",
    type: "屏風",
    typeen: "byoubu",
    kotobagaki: false,
    sourceImageUrl: "https://asia.si.edu/object/F1906.231-232/",
    sourceImage: "Waves at Matsushima（フリーア美術館）",
    sourceEkotoba: "",
    emakis: [
      {
        cat: "ekotoba",
        chapter: "右隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: true,
        cat: "image",
        srcSp: "/matsusima_01-375.webp",
        srcTb: "/matsusima_01-800.webp",
        src: "/matsusima_01-1080.webp",
        name: "matsusima_01.webp",
      },
      {
        cat: "ekotoba",
        chapter: "左隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: false,
        cat: "image",
        srcSp: "/matsusima_02-375.webp",
        srcTb: "/matsusima_02-800.webp",
        src: "/matsusima_02-1080.webp",
        name: "matsusima_02.webp",
      },
    ],
  },
  {
    id: 22,
    title: "雲龍図屏風",
    titleen: "unryuzu",
    author: "俵屋宗達",
    backgroundImage: "/washi-pattern-01.webp",
    video: "",
    thumb: "/unryuzu_thumb.webp",
    thumb2: "/unryuzu_thumb.webp",
    metadesc: "",
    desc: "",
    era: "安土・桃山",
    eraen: "aduchimomoyama",
    gif: "",
    type: "屏風",
    typeen: "byoubu",
    kotobagaki: false,
    sourceImageUrl: "https://asia.si.edu/object/F1905.230/",
    sourceImage: "Dragons and Clouds（フリーア美術館）",
    sourceEkotoba: "",
    emakis: [
      {
        cat: "ekotoba",
        chapter: "右隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: true,
        cat: "image",
        srcSp: "/unryuzu_01-375.webp",
        srcTb: "/unryuzu_01-800.webp",
        src: "/unryuzu_01-1080.webp",
        name: "unryuzu_01.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/unryuzu_02-375.webp",
        srcTb: "/unryuzu_02-800.webp",
        src: "/unryuzu_02-1080.webp",
        name: "unryuzu_02.webp",
      },
      {
        cat: "ekotoba",
        chapter: "左隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: false,
        cat: "image",
        srcSp: "/unryuzu_03-375.webp",
        srcTb: "/unryuzu_03-800.webp",
        src: "/unryuzu_03-1080.webp",
        name: "unryuzu_03.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/unryuzu_04-375.webp",
        srcTb: "/unryuzu_04-800.webp",
        src: "/unryuzu_04-1080.webp",
        name: "unryuzu_04.webp",
      },
    ],
  },
  {
    id: 23,
    title: "源氏物語図屏風",
    titleen: "genji_asagao",
    edition: "朝顔",
    genjieslug: [{ id: "20", title: "朝顔", ruby: "あさがお", path: "asagao" }],
    author: "俵屋宗達",
    backgroundImage: "/washi-pattern-01.webp",
    video: "",
    thumb: "/genji_asagao_thumb.webp",
    thumb2: "/genji_asagao_thumb.webp",
    waka_kami:
      "秋はてて　霧の<ruby>籬<rp>(</rp><rt>まがき</rt><rp>)</rp></ruby>にむすぼほれ",
    waka_simo: "あるかなきかに　うつる朝顔",
    metadesc: "",
    desc: "",
    era: "安土・桃山",
    eraen: "aduchimomoyama",
    gif: "",
    type: "屏風",
    typeen: "byoubu",
    kotobagaki: false,
    sourceImageUrl: "https://asia.si.edu/object/F1903.101-102/",
    sourceImage:
      "Court Ladies among cherry trees (left); Cherry blossoms, a high fence and retainers (right)（フリーア美術館）",
    sourceEkotoba: "",
    emakis: [
      {
        cat: "ekotoba",
        chapter: "右隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: true,
        cat: "image",
        srcSp: "/genji_asagao_01-375.webp",
        srcTb: "/genji_asagao_01-800.webp",
        src: "/genji_asagao_01-1080.webp",
        name: "genji_asagao_01.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/genji_asagao_02-375.webp",
        srcTb: "/genji_asagao_02-800.webp",
        src: "/genji_asagao_02-1080.webp",
        name: "genji_asagao_02.webp",
      },
      {
        cat: "ekotoba",
        chapter: "左隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: false,
        cat: "image",
        srcSp: "/genji_asagao_03-375.webp",
        srcTb: "/genji_asagao_03-800.webp",
        src: "/genji_asagao_03-1080.webp",
        name: "genji_asagao_03.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/genji_asagao_04-375.webp",
        srcTb: "/genji_asagao_04-800.webp",
        src: "/genji_asagao_04-1080.webp",
        name: "genji_asagao_04.webp",
      },
    ],
  },
  {
    id: 24,
    title: "松竹梅",
    titleen: "syouchikubai",
    author: "横山大観",
    backgroundImage: "/washi-pattern-01.webp",
    video: "",
    thumb: "/syouchikubai_thumb.webp",
    thumb2: "/syouchikubai_thumb.webp",
    metadesc: "",
    desc: "",
    era: "明治",
    eraen: "meiji",
    gif: "",
    type: "屏風",
    typeen: "byoubu",
    kotobagaki: false,
    sourceImageUrl:
      "https://colbase.nich.go.jp/collection_items/tnm/A-11783?locale=ja",
    sourceImage: "松竹梅（ColBase）",
    sourceEkotoba: "",
    emakis: [
      {
        cat: "ekotoba",
        chapter: "右隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: true,
        cat: "image",
        srcSp: "/syouchikubai_01-375.webp",
        srcTb: "/syouchikubai_01-800.webp",
        src: "/syouchikubai_01-1080.webp",
        name: "syouchikubai_01.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/syouchikubai_02-375.webp",
        srcTb: "/syouchikubai_02-800.webp",
        src: "/syouchikubai_02-1080.webp",
        name: "syouchikubai_02.webp",
      },
      {
        cat: "ekotoba",
        chapter: "左隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: false,
        cat: "image",
        srcSp: "/syouchikubai_03-375.webp",
        srcTb: "/syouchikubai_03-800.webp",
        src: "/syouchikubai_03-1080.webp",
        name: "syouchikubai_03.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/syouchikubai_04-375.webp",
        srcTb: "/syouchikubai_04-800.webp",
        src: "/syouchikubai_04-1080.webp",
        name: "syouchikubai_04.webp",
      },
    ],
  },
  {
    id: 25,
    title: "溪山四時図屏風",
    titleen: "keizanyoizu",
    author: "川合玉堂",
    backgroundImage: "/washi-pattern-01.webp",
    video: "",
    thumb: "/keizanyoizu_thumb.webp",
    thumb2: "/keizanyoizu_thumb.webp",
    metadesc: "",
    desc: "",
    era: "明治",
    eraen: "meiji",
    gif: "",
    type: "屏風",
    typeen: "byoubu",
    kotobagaki: false,
    sourceImageUrl:
      "https://colbase.nich.go.jp/collection_items/tnm/A-11782?locale=ja",
    sourceImage: "溪山四時図屏風（ColBase）",
    sourceEkotoba: "",
    emakis: [
      {
        cat: "ekotoba",
        chapter: "右隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: true,
        cat: "image",
        srcSp: "/keizanyoizu_01-375.webp",
        srcTb: "/keizanyoizu_01-800.webp",
        src: "/keizanyoizu_01-1080.webp",
        name: "keizanyoizu_01.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/keizanyoizu_02-375.webp",
        srcTb: "/keizanyoizu_02-800.webp",
        src: "/keizanyoizu_02-1080.webp",
        name: "keizanyoizu_02.webp",
      },
      {
        cat: "ekotoba",
        chapter: "左隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: false,
        cat: "image",
        srcSp: "/keizanyoizu_03-375.webp",
        srcTb: "/keizanyoizu_03-800.webp",
        src: "/keizanyoizu_03-1080.webp",
        name: "keizanyoizu_03.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/keizanyoizu_04-375.webp",
        srcTb: "/keizanyoizu_04-800.webp",
        src: "/keizanyoizu_04-1080.webp",
        name: "keizanyoizu_04.webp",
      },
    ],
  },
  {
    id: 26,
    title: "牧馬図屏風",
    titleen: "makibazu",
    author: "長谷川等伯",
    backgroundImage: "/washi-pattern-01.webp",
    video: "",
    thumb: "/makibazu_thumb.webp",
    thumb2: "/makibazu_thumb.webp",
    metadesc: "",
    desc: "",
    era: "安土・桃山",
    eraen: "aduchimomoyama",
    gif: "",
    type: "屏風",
    typeen: "byoubu",
    kotobagaki: false,
    sourceImageUrl:
      "https://colbase.nich.go.jp/collection_items/tnm/A-56?locale=ja",
    sourceImage: "牧馬図屏風（ColBase）",
    sourceEkotoba: "",
    emakis: [
      {
        cat: "ekotoba",
        chapter: "右隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: true,
        cat: "image",
        srcSp: "/makibazu_01-375.webp",
        srcTb: "/makibazu_01-800.webp",
        src: "/makibazu_01-1080.webp",
        name: "makibazu_01.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/makibazu_02-375.webp",
        srcTb: "/makibazu_02-800.webp",
        src: "/makibazu_02-1080.webp",
        name: "makibazu_02.webp",
      },
      {
        cat: "ekotoba",
        chapter: "左隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: false,
        cat: "image",
        srcSp: "/makibazu_03-375.webp",
        srcTb: "/makibazu_03-800.webp",
        src: "/makibazu_03-1080.webp",
        name: "makibazu_03.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/makibazu_04-375.webp",
        srcTb: "/makibazu_04-800.webp",
        src: "/makibazu_04-1080.webp",
        name: "makibazu_04.webp",
      },
    ],
  },
  {
    id: 27,
    title: "源氏物語図屏風",
    titleen: "sekiyazu",
    edition: "関屋",
    genjieslug: [{ id: "16", title: "関屋", ruby: "せきや", path: "sekiya" }],
    author: "俵屋宗達",
    backgroundImage: "/washi-pattern-01.webp",
    video: "",
    thumb: "/sekiyazu_thumb.webp",
    thumb2: "/sekiyazu_thumb.webp",
    waka_kami: "わくらはに　行き逢あふみちを　頼みしも",
    waka_simo: "なほかひなしや　塩ならぬ海",
    metadesc: "",
    desc: "",
    era: "安土・桃山",
    eraen: "aduchimomoyama",
    gif: "",
    type: "屏風",
    typeen: "byoubu",
    kotobagaki: false,
    sourceImageUrl:
      "https://colbase.nich.go.jp/collection_items/tnm/A-12190?locale=ja",
    sourceImage: "関屋図屏風（ColBase）",
    sourceEkotoba: "",
    emakis: [
      {
        cat: "ekotoba",
        chapter: "六曲一隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: true,
        cat: "image",
        srcSp: "/sekiyazu_01-375.webp",
        srcTb: "/sekiyazu_01-800.webp",
        src: "/sekiyazu_01-1080.webp",
        name: "sekiyazu_01.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/sekiyazu_02-375.webp",
        srcTb: "/sekiyazu_02-800.webp",
        src: "/sekiyazu_02-1080.webp",
        name: "sekiyazu_02.webp",
      },
    ],
  },
  {
    id: 29,
    title: "鵜",
    titleen: "u",
    author: "下村観山",
    backgroundImage: "/washi-pattern-01.webp",
    video: "",
    thumb: "/u_thumb.webp",
    thumb2: "/u_thumb.webp",
    metadesc: "",
    desc: "",
    era: "明治",
    eraen: "meiji",
    gif: "",
    type: "屏風",
    typeen: "byoubu",
    kotobagaki: false,
    sourceImageUrl:
      "https://colbase.nich.go.jp/collection_items/tnm/A-10514?locale=ja",
    sourceImage: "鵜（ColBase）",
    sourceEkotoba: "",
    emakis: [
      {
        cat: "ekotoba",
        chapter: "右隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: true,
        cat: "image",
        srcSp: "/u_01-375.webp",
        srcTb: "/u_01-800.webp",
        src: "/u_01-1080.webp",
        name: "u_01.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/u_02-375.webp",
        srcTb: "/u_02-800.webp",
        src: "/u_02-1080.webp",
        name: "u_02.webp",
      },
      {
        cat: "ekotoba",
        chapter: "左隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: false,
        cat: "image",
        srcSp: "/u_03-375.webp",
        srcTb: "/u_03-800.webp",
        src: "/u_03-1080.webp",
        name: "u_03.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/u_04-375.webp",
        srcTb: "/u_04-800.webp",
        src: "/u_04-1080.webp",
        name: "u_04.webp",
      },
    ],
  },
  {
    id: 30,
    title: "弱法師",
    titleen: "yoroboushi",
    author: "下村観山",
    backgroundImage: "/washi-pattern-01.webp",
    video: "",
    thumb: "/yoroboushi_thumb.webp",
    thumb2: "yoroboushi_thumb.webp",
    metadesc: "",
    desc: "",
    era: "明治",
    eraen: "meiji",
    gif: "",
    type: "屏風",
    typeen: "byoubu",
    kotobagaki: false,
    sourceImageUrl:
      "https://colbase.nich.go.jp/collection_items/tnm/A-10508?locale=ja",
    sourceImage: "弱法師（ColBase）",
    sourceEkotoba: "",
    emakis: [
      {
        cat: "ekotoba",
        chapter: "右隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: true,
        cat: "image",
        srcSp: "/yoroboushi_01-375.webp",
        srcTb: "/yoroboushi_01-800.webp",
        src: "/yoroboushi_01-1080.webp",
        name: "yoroboushi_01.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/yoroboushi_02-375.webp",
        srcTb: "/yoroboushi_02-800.webp",
        src: "/yoroboushi_02-1080.webp",
        name: "yoroboushi_02.webp",
      },
      {
        cat: "ekotoba",
        chapter: "左隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: false,
        cat: "image",
        srcSp: "/yoroboushi_03-375.webp",
        srcTb: "/yoroboushi_03-800.webp",
        src: "/yoroboushi_03-1080.webp",
        name: "yoroboushi_03.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/yoroboushi_04-375.webp",
        srcTb: "/yoroboushi_04-800.webp",
        src: "/yoroboushi_04-1080.webp",
        name: "yoroboushi_04.webp",
      },
    ],
  },
  {
    id: 30,
    title: "春雨図屏風",
    titleen: "harusame",
    author: "下村観山",
    backgroundImage: "/washi-pattern-01.webp",
    video: "",
    thumb: "/harusame_thumb.webp",
    thumb2: "harusame_thumb.webp",
    metadesc: "",
    desc: "",
    era: "明治",
    eraen: "meiji",
    gif: "",
    type: "屏風",
    typeen: "byoubu",
    kotobagaki: false,
    sourceImageUrl:
      "https://colbase.nich.go.jp/collection_items/tnm/A-10517?locale=ja",
    sourceImage: "春雨図屏風（ColBase）",
    sourceEkotoba: "",
    emakis: [
      {
        cat: "ekotoba",
        chapter: "右隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: true,
        cat: "image",
        srcSp: "/harusame_01-375.webp",
        srcTb: "/harusame_01-800.webp",
        src: "/harusame_01-1080.webp",
        name: "harusame_01.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/harusame_02-375.webp",
        srcTb: "/harusame_02-800.webp",
        src: "/harusame_02-1080.webp",
        name: "harusame_02.webp",
      },
      {
        cat: "ekotoba",
        chapter: "左隻",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: false,
        cat: "image",
        srcSp: "/harusame_03-375.webp",
        srcTb: "/harusame_03-800.webp",
        src: "/harusame_03-1080.webp",
        name: "harusame_03.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/harusame_04-375.webp",
        srcTb: "/harusame_04-800.webp",
        src: "/harusame_04-1080.webp",
        name: "harusame_04.webp",
      },
    ],
  },
  {
    id: 31,
    title: "源氏物語図屏風",
    titleen: "genjibyobu_eawasekocyo",
    edition: "絵合・胡蝶",
    genjieslug: [
      { id: "17", title: "絵合", ruby: "えあわせ", path: "eawase" },
      { id: "24", title: "胡蝶", ruby: "こてふ", path: "kotefu" },
    ],
    author: "狩野〈晴川院〉養信",
    backgroundImage: "/washi-pattern-01.webp",
    video: "",
    thumb: "/genjibyobu_eawasekocyo_01-1080.webp",
    thumb2: "genjibyobu_eawasekocyo_01-1080.webp",
    waka_kami: "別れ路に　添へし小櫛を　かごとにて",
    waka_simo: "はるけき中と　神やいさめし",
    metadesc: "",
    desc: "",
    era: "江戸",
    eraen: "edo",
    gif: "",
    type: "屏風",
    typeen: "byoubu",
    kotobagaki: true,
    sourceImageUrl:
      "https://colbase.nich.go.jp/collection_items/tnm/A-12373?locale=ja",
    sourceImage: "源氏物語図屏風（絵合・胡蝶）（ColBase）",
    sourceEkotoba: "",
    emakis: [
      {
        cat: "ekotoba",
        chapter: "【右隻】　絵合",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: true,
        cat: "image",
        srcSp: "/genjibyobu_eawasekocyo_01-375.webp",
        srcTb: "/genjibyobu_eawasekocyo_01-800.webp",
        src: "/genjibyobu_eawasekocyo_01-1080.webp",
        name: "genjibyobu_eawasekocyo_01.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/genjibyobu_eawasekocyo_02-375.webp",
        srcTb: "/genjibyobu_eawasekocyo_02-800.webp",
        src: "/genjibyobu_eawasekocyo_02-1080.webp",
        name: "genjibyobu_eawasekocyo_02.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/genjibyobu_eawasekocyo_03-375.webp",
        srcTb: "/genjibyobu_eawasekocyo_03-800.webp",
        src: "/genjibyobu_eawasekocyo_03-1080.webp",
        name: "genjibyobu_eawasekocyo_03.webp",
      },
      {
        cat: "ekotoba",
        chapter: "【左隻】　胡蝶",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: false,
        cat: "image",
        srcSp: "/genjibyobu_eawasekocyo_04-375.webp",
        srcTb: "/genjibyobu_eawasekocyo_04-800.webp",
        src: "/genjibyobu_eawasekocyo_04-1080.webp",
        name: "genjibyobu_eawasekocyo_04.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/genjibyobu_eawasekocyo_05-375.webp",
        srcTb: "/genjibyobu_eawasekocyo_05-800.webp",
        src: "/genjibyobu_eawasekocyo_05-1080.webp",
        name: "genjibyobu_eawasekocyo_05.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/genjibyobu_eawasekocyo_06-375.webp",
        srcTb: "/genjibyobu_eawasekocyo_06-800.webp",
        src: "/genjibyobu_eawasekocyo_06-1080.webp",
        name: "genjibyobu_eawasekocyo_06.webp",
      },
    ],
  },
  {
    id: 32,
    title: "源氏物語図屏風",
    titleen: "genjibyobu_akashi_yomogiu",
    genjieslug: [
      { id: "13", title: "明石", ruby: "あかし", path: "akashi" },
      { id: "15", title: "蓬生", ruby: "よもぎふ", path: "yomogifu" },
    ],
    edition: "明石・蓬生",
    author: "",
    backgroundImage: "/washi-pattern-01.webp",
    video: "",
    thumb: "/genjibyobu_akashi_yomogiu_01-1080.webp",
    thumb2: "genjibyobu_akashi_yomogiu_01-1080.webp",
    waka_kami: "泡と見る　淡路の島のあはれさへ",
    waka_simo: "残るくまなく　澄める夜の月",
    metadesc: "",
    desc: "",
    era: "安土・桃山",
    eraen: "aduchimomoyama",
    gif: "",
    type: "屏風",
    typeen: "byoubu",
    kotobagaki: false,
    sourceImageUrl:
      "https://colbase.nich.go.jp/collection_items/tnm/A-11153?locale=ja",
    sourceImage: "源氏物語図屏風（明石・蓬生）（ColBase）",
    sourceEkotoba: "",
    emakis: [
      {
        cat: "ekotoba",
        chapter: "【右隻】　明石",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: true,
        cat: "image",
        srcSp: "/genjibyobu_akashi_yomogiu_01-375.webp",
        srcTb: "/genjibyobu_akashi_yomogiu_01-800.webp",
        src: "/genjibyobu_akashi_yomogiu_01-1080.webp",
        name: "genjibyobu_akashi_yomogiu_01.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/genjibyobu_akashi_yomogiu_02-375.webp",
        srcTb: "/genjibyobu_akashi_yomogiu_02-800.webp",
        src: "/genjibyobu_akashi_yomogiu_02-1080.webp",
        name: "genjibyobu_akashi_yomogiu_02.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/genjibyobu_akashi_yomogiu_03-375.webp",
        srcTb: "/genjibyobu_akashi_yomogiu_03-800.webp",
        src: "/genjibyobu_akashi_yomogiu_03-1080.webp",
        name: "genjibyobu_akashi_yomogiu_03.webp",
      },
      {
        cat: "ekotoba",
        chapter: "【左隻】　蓬生",
        kobun: "",
        gendaibun: "",
        phrase: [{}],
      },
      {
        load: false,
        cat: "image",
        srcSp: "/genjibyobu_akashi_yomogiu_04-375.webp",
        srcTb: "/genjibyobu_akashi_yomogiu_04-800.webp",
        src: "/genjibyobu_akashi_yomogiu_04-1080.webp",
        name: "genjibyobu_akashi_yomogiu_04.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/genjibyobu_akashi_yomogiu_05-375.webp",
        srcTb: "/genjibyobu_akashi_yomogiu_05-800.webp",
        src: "/genjibyobu_akashi_yomogiu_05-1080.webp",
        name: "genjibyobu_akashi_yomogiu_05.webp",
      },
      {
        load: false,
        cat: "image",
        srcSp: "/genjibyobu_akashi_yomogiu_06-375.webp",
        srcTb: "/genjibyobu_akashi_yomogiu_06-800.webp",
        src: "/genjibyobu_akashi_yomogiu_06-1080.webp",
        name: "genjibyobu_akashi_yomogiu_06.webp",
      },
    ],
  },
];

export default dataByoubus;
