export const gridImages = [
  {
    id: "1",
    image: "/cyoujyuu_yamazaki_kou_13-1080.webp",
    title: "鳥獣人物戯画絵巻 甲巻",
    path: "cyoujyujinbutsugiga_kou#s15",
    desc: "猿は蛙たちにの怒りを買い...",
    eracolor: "orange",
    bln: false,
  },
  {
    id: "2",
    image: "/images/gridImage_haseo.png",
    title: "長谷雄草紙",
    path: "haseozoushi#s10",
    desc: "長谷雄が一心に祈ると、鬼は退散し...",
    eracolor: "green",
    bln: false,
  },
  {
    id: "3",
    image: "/kusouzu_01-1080.webp",
    title: "九相図巻",
    path: "kusouzumaki",
    desc: "美しい女性の肉体は無常にも蝕まれ...",
    eracolor: "green",
    bln: false,
  },
  {
    id: "4",
    image: "/tokugawagyouretsu_16-1080.webp",
    title: "徳川種姫婚礼行列図",
    path: "tokugawatanehimegyouretuzu#s15",
    desc: "ぞろぞろと婚礼の行列は続いていき...",
    eracolor: "skyblue",
    bln: false,
  },
  {
    id: "5",
    image: "/jigokusoushi_genke_08-1080.webp",
    title: "地獄草紙（原家本）　",
    path: "jigokusoushi_genke#s6",
    desc: "地獄に落ちた亡者は火炎を上げる鶏に襲われ...",
    eracolor: "orange",
    bln: false,
  },
];
