export const gridImages = [
  {
    id: "1",
    image: "/cyoujyuu_yamazaki_kou_13-1080.webp",
    title: "鳥獣人物戯画絵巻 甲巻",
    path: "cyoujyujinbutsugiga_kou#s15",
    desc: "猿は蛙たちの怒りを買い...",
    descen: "The monkey got angry with the frogs...",
    eracolor: "orange",
    bln: false,
  },
  {
    id: "2",
    image: "/haseozoushi_17-1080.webp",
    title: "長谷雄草紙",
    path: "haseozoushi#s16",
    desc: "長谷雄が一心に祈ると、鬼は退散し...",
    descen: "Haseo prayed earnestly, and the demon disappeared...",
    eracolor: "green",
    bln: false,
  },
  {
    id: "3",
    image: "/kusouzu_01-1080.webp",
    title: "九相図巻",
    path: "kusouzumaki",
    desc: "美しい女性の肉体は無常にも蝕まれ...",
    descen: "A beautiful woman's body is constantly undermined...",
    eracolor: "green",
    bln: false,
  },
  {
    id: "4",
    image: "/tokugawagyouretsu_16-1080.webp",
    title: "徳川種姫婚礼行列図",
    path: "tokugawatanehimegyouretuzu#s15",
    desc: "ぞろぞろと婚礼の行列は続いていき...",
    descen: "The wedding procession goes on and on...",
    eracolor: "skyblue",
    bln: false,
  },
  {
    id: "5",
    image: "/jigokusoushi_genke_08-1080.webp",
    title: "地獄草紙（原家本）　",
    path: "jigokusoushi_genke#s6",
    desc: "地獄に落ちた亡者は火炎を上げる鶏に襲われ...",
    descen: "The dead who fell into hell are attacked by flaming chickens...",
    eracolor: "orange",
    bln: false,
  },
  {
    id: "6",
    image: "/cyoujyuu_yamazaki_kou_13-1080.webp",
    title: "鳥獣人物戯画絵巻 甲巻",
    path: "cyoujyujinbutsugiga_kou#s15",
    desc: "猿は蛙たちの怒りを買い...",
    descen: "The monkey got angry with the frogs...",
    eracolor: "orange",
    bln: false,
  },
  {
    id: "7",
    image: "/haseozoushi_17-1080.webp",
    title: "長谷雄草紙",
    path: "haseozoushi#s16",
    desc: "長谷雄が一心に祈ると、鬼は退散し...",
    descen: "Haseo prayed earnestly, and the demon disappeared...",
    eracolor: "green",
    bln: false,
  },
  {
    id: "8",
    image: "/kusouzu_01-1080.webp",
    title: "九相図巻",
    path: "kusouzumaki",
    desc: "美しい女性の肉体は無常にも蝕まれ...",
    descen: "A beautiful woman's body is constantly undermined...",
    eracolor: "green",
    bln: false,
  },
  {
    id: "9",
    image: "/tokugawagyouretsu_16-1080.webp",
    title: "徳川種姫婚礼行列図",
    path: "tokugawatanehimegyouretuzu#s15",
    desc: "ぞろぞろと婚礼の行列は続いていき...",
    descen: "The wedding procession goes on and on...",
    eracolor: "skyblue",
    bln: false,
  },
  {
    id: "10",
    image: "/jigokusoushi_genke_08-1080.webp",
    title: "地獄草紙（原家本）　",
    path: "jigokusoushi_genke#s6",
    desc: "地獄に落ちた亡者は火炎を上げる鶏に襲われ...",
    descen: "The dead who fell into hell are attacked by flaming chickens...",
    eracolor: "orange",
    bln: false,
  },
];
